### ISSUE TITLE
Windows: Chocolatey not being recognized in PATH

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-jenkins#1812]
Windows: Chocolatey specific installs are failing, even though chocolatey bootstrap seems to work as expected. This impacts all versions of Windows:

- 2016
- 2019
- 2022

Any state trying to install via `chocolatey.installed` will fail with:

```
Chocolatey not installed. Use chocolatey.bootstrap to install the Chocolatey package manager.
```

Example failed state:

```
      ID: rsync
Function: chocolatey.installed
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            ...
            ...
            ...
          salt.exceptions.CommandExecutionError: Chocolatey not installed. Use chocolatey.bootstrap to install the Chocolatey package manager.
```

Even though bootstrap shows as success:

```bash
Bootstrapping Chocolatey

Running Command: 'C:\Windows\TEMP\salt\salt-call.exe --local --log-level=warning --config-dir=c:\salt-provision\conf --retcode-passthrough chocolatey.bootstrap'
[WARNING ][salt._logging.impl:803 ] Failed to open log file, do you have permission to write to c:\salt-provision\logs\minion.log?
[WARNING ][salt._logging.impl                       :803 ] Failed to open log file, do you have permission to write to c:\salt-provision\logs\minion.log?
C:\Windows\TEMP\salt\lib\site-packages\salt\ext\tornado\netutil.py:493: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  context = ssl.SSLContext(
local:
    Forcing web requests to allow TLS v1.2 (Required for requests to Chocolatey.org)
    Getting latest version of the Chocolatey package for download.
    Not using proxy.
    Getting Chocolatey from https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0.
    Downloading https://community.chocolatey.org/api/v2/package/chocolatey/2.0.0 to C:\Windows\TEMP\chocolatey\chocoInstall\chocolatey.zip
    Not using proxy.
    Extracting C:\Windows\TEMP\chocolatey\chocoInstall\chocolatey.zip to C:\Windows\TEMP\chocolatey\chocoInstall
    Installing Chocolatey on the local machine
    Creating ChocolateyInstall as an environment variable (targeting 'Machine')
      Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
    WARNING: It's very likely you will need to close and reopen your shell
      before you can use choco.
    Restricting write permissions to Administrators
    We are setting up the Chocolatey package repository.
    The packages themselves go to 'C:\ProgramData\chocolatey\lib'
      (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
    A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
      and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

    Creating Chocolatey folders if they do not already exist.

    chocolatey.nupkg file not installed in lib.
     Attempting to locate it from bootstrapper.
    PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
    WARNING: Not setting tab completion: Current user is SYSTEM user.
    Chocolatey (choco.exe) is now ready.
    You can call choco from anywhere, command line or powershell by typing choco.
    Run choco /? for a list of functions.
    You may need to shut down and restart powershell and/or consoles
     first prior to using choco.
    Ensuring Chocolatey commands are on the path
    Ensuring chocolatey.nupkg is in the lib folder

Running Command 'C:\Windows\TEMP\salt\salt-call.exe --local --log-level=warning --config-dir=c:\salt-provision\conf --retcode-passthrough chocolatey.bootstrap' Succeeded!
```

Example job:

- https://github.com/saltstack/salt-jenkins/actions/runs/5360401626/jobs/9725239754

**Comment by ScriptAutomate** [comment]
Related:

- https://github.com/saltstack/salt/issues/64427

Workaround may involve something similar to the following:

```yaml
# Is chocolatey installed?
Chocolatey is installed without symlink:
  file.exists:
    - name: 'C:\ProgramData\chocolatey\choco.exe'

# Bootstrap Chocolatey package manager
Bootstrap Chocolatey:
  module.run:
    - chocolatey.bootstrap: []
    - onfail:
      - Chocolatey is installed without symlink

# Ensure there is a symlink from chocolatey.exe to choco.exe
Chocolatey is installed:
  file.symlink:
    - name: 'C:\ProgramData\chocolatey\chocolatey.exe'
    - target: 'C:\ProgramData\chocolatey\choco.exe'
    - require:
      - Chocolatey is installed without symlink
```
